#!/usr/bin/env python3

import colors as c
import time

try:
    while True: 
        print(c.red + "S" + c.orange + "A" + c.yellow + "N" + c.green + "D" + c.blue + "W" + c.violet + "I" + c.magenta + "T" + c.red + "C" + c.orange + "H")
except KeyboardInterrupt:

    print(c.clear)
    print(c.green + " xXSanwitchSenpaiXx will always be known for making his delicious sandwitchs. When u Read this the Senpai of sandwitchs will be in the big sandwitch in the sky ;(. Whenever u miss me eat a sandwitch")
    print(c.blue + " BLAKE SHALL EAT ALL THE SANDWITCHS WITH THE POWER OF THE STICK!!!!!!!!!!!!!!!!!")


